// flow-typed signature: ca113b20c41b1aca221cb926c93a9eec
// flow-typed version: <<STUB>>/rn-swipe-button_v^1.3.0/flow_v0.134.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rn-swipe-button'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rn-swipe-button' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rn-swipe-button/src/components/SwipeButton' {
  declare module.exports: any;
}

declare module 'rn-swipe-button/src/components/SwipeButton/styles' {
  declare module.exports: any;
}

declare module 'rn-swipe-button/src/components/SwipeThumb' {
  declare module.exports: any;
}

declare module 'rn-swipe-button/src/components/SwipeThumb/styles' {
  declare module.exports: any;
}

declare module 'rn-swipe-button/src/constants' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rn-swipe-button/index' {
  declare module.exports: $Exports<'rn-swipe-button'>;
}
declare module 'rn-swipe-button/index.js' {
  declare module.exports: $Exports<'rn-swipe-button'>;
}
declare module 'rn-swipe-button/src/components/SwipeButton/index' {
  declare module.exports: $Exports<'rn-swipe-button/src/components/SwipeButton'>;
}
declare module 'rn-swipe-button/src/components/SwipeButton/index.js' {
  declare module.exports: $Exports<'rn-swipe-button/src/components/SwipeButton'>;
}
declare module 'rn-swipe-button/src/components/SwipeButton/styles.js' {
  declare module.exports: $Exports<'rn-swipe-button/src/components/SwipeButton/styles'>;
}
declare module 'rn-swipe-button/src/components/SwipeThumb/index' {
  declare module.exports: $Exports<'rn-swipe-button/src/components/SwipeThumb'>;
}
declare module 'rn-swipe-button/src/components/SwipeThumb/index.js' {
  declare module.exports: $Exports<'rn-swipe-button/src/components/SwipeThumb'>;
}
declare module 'rn-swipe-button/src/components/SwipeThumb/styles.js' {
  declare module.exports: $Exports<'rn-swipe-button/src/components/SwipeThumb/styles'>;
}
declare module 'rn-swipe-button/src/constants/index' {
  declare module.exports: $Exports<'rn-swipe-button/src/constants'>;
}
declare module 'rn-swipe-button/src/constants/index.js' {
  declare module.exports: $Exports<'rn-swipe-button/src/constants'>;
}
